# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Risas-Pizzas
email: robert.joseph.freund@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple pizza restaurant project website.
baseurl: "/Risas-Pizzas" # the subpath of your site, e.g. /blog
url: "https://rjfreund.github.io" # the base hostname & protocol for your site
twitter_username: rj_freund
github_username:  rjfreund

# Build settings
markdown: kramdown
